server:
    port: 8080

spirng:
    cloud:
        gateway: 
            routes:
                - id: pruebas-service
                  uri: http://localhost:8081 #URI del servicio
                  predicates:
                      - Path=/api/pruebas/**
                      - Path=/api/empleados/**


jwt:
    expiration: 3600000
    secret-key: "rocco"
