server:
    port: 8080

spring:
    cloud:
        gateway: 
            routes:
                - id: pruebas-service
                  uri: http://localhost:8081 #URI del servicio
                  predicates:
                      - Path=/api/pruebas/**
                      - Path=/api/empleados/**
                - id: reportes-service
                  uri: http://localhost:8082
                  predicates:
                      - Path=/api/reportes/**


jwt:
    expiration: 3600000
    secret-key: "rocco"


