server:
  port: 8081  # Puerto en el que se ejecutará el API Gateway

spring:
  application:
    name: api-gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://labsys.frc.utn.edu.ar/aim/realms/backend-tps  # URL del Keycloak Realm
  cloud:
    gateway:
      routes:
        - id: pruebas-service
          uri: http://localhost:8082  # puerto del servicio de pruebas
          predicates:
            - Path=/api/empleados/**
            - Path=/api/pruebas/**
          metadata:
            roles: EMPLEADO


keycloak:
  realm: backend-tps
  auth-server-url: https://labsys.frc.utn.edu.ar/aim/
  client-id: cliente-tpi
  client-secret: ZmiMMce6zh4xKHde1FFKbfkiThDyYpyn
  confidential-port: 0
  principal-attribute: preferred_username

external:
  api:
    configuracion-url: "https://labsys.frc.utn.edu.ar/apps-disponibilizadas/backend/api/v1/configuracion/"

logging:
  level:
    org.springframework.cloud.gateway: DEBUG



