# Usa una imagen ligera de Java 21
FROM openjdk:21-jdk-slim

# Establece el directorio de trabajo
WORKDIR /pruebas

# Copia el archivo JAR generado por Spring Boot al contenedor
COPY target/pruebas-0.0.1-SNAPSHOT.jar pruebas.jar

# Expone el puerto en el que el API Gateway estará escuchando
EXPOSE 8081

# Configura el comando para ejecutar la aplicación
ENTRYPOINT ["java", "-jar", "pruebas.jar"]